### ISSUE TITLE
[Bug]: Sleeping in hammock makes it morning

### ISSUE THREAD

**Issue by TNoStone** [illusivesoulworks/comforts#138]
### Minecraft Version

1.20.1

### What happened?

Instead of it making it night, it makes it day, when sleeping in the hammock. Direwolf20 pack

### How do you trigger this bug?

1. be on direwolf20 pack
2. sleep in hammock
3.
...

### Loader

Forge

### Loader Version

Forge 47.1.84

### Mod Version

6.3.4+1.20.1

**Comment by TheIllusiveC4** [comment]
I can confirm the bug exists in the pack (and does not exist standalone) but there are too many potential mod conflicts and configurations to isolate the cause. I've done some cursory investigation but haven't yielded any results. It would be best to either report this to the modpack developer or narrow down the selection of mods needed to reproduce the bug.

**Comment by goreae** [comment]
I've installed Vampirism into my version of DW20 1.20, and the coffin has the same issue. I did my own testing and found that it's Ad Astra's fault. Made an instance with just Ad Astra, Comforts, and their required libraries, and it sets the time to morning. My guess is that Ad Astra makes changes to the sleep mechanics so you can sleep in their dimensions, but it breaks and "sleep through the day" mechanics that other mods use.

**Comment by goreae** [comment]
Ad Astra fixed the bug on their end. https://github.com/terrarium-earth/Ad-Astra/issues/470
